CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'Listener',
  bio TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
